# speed up zsh completions
autoload -Uz compinit
compinit -C

# alias section
alias switchyubikey="gpg-connect-agent 'scd serialno' 'learn --force' /bye"
alias codel="code $HOME/master-thesis/longevity.code-workspace"

# load zsh plugins via antibody
antibody bundle < ~/.zsh_plugins.txt > ~/.zsh_plugins.sh
source ~/.zsh_plugins.sh

# zsh plugin customization
export ZSH_PLUGINS_ALIAS_TIPS_TEXT="Alias tip: "


# pyenv setup
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# using gpg as ssh agent
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent
export PATH="/usr/local/opt/ruby/bin:$PATH"

# the fuck configuraiton
eval $(thefuck --alias)
