# speed up zsh completions
autoload -Uz compinit
compinit -C

# alias section
alias switchyubikey="gpg-connect-agent 'scd serialno' 'learn --force' /bye"
alias lg="lazygit"
alias fl="bundle exec fastlane"
alias fastlane="bundle exec fastlane"
alias gfk="./gradlew ktlintFormat && ./gradlew ktlintCheck"

# load zsh plugins via antidote
source $HOME/.antidote/antidote.zsh
antidote load ${ZDOTDIR:-$HOME}/.zsh_plugins.txt

# load startship
eval "$(starship init zsh)"

# zsh plugin customization
export ZSH_PLUGINS_ALIAS_TIPS_TEXT="Alias tip: "

# pyenv setup
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# ruby setup
RUBY_HOME=/opt/homebrew/opt/ruby/bin
export PATH="$RUBY_HOME:$PATH"
GEM_PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin"

# using gpg as ssh agent
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

# export ruby path ## note: commented for now, I want to figure out where this is required
# export PATH="/usr/local/opt/ruby/bin:$PATH"

# the fuck configuraiton
eval $(thefuck --alias)

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
